# Netlify instructions to control build

[build]
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.78.2" # substitute whichever version you prefer; this was as of 2020-11-19
  HUGO_ENV = "production"
  