# Netlify instructions to control build

[build]
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.74.3" # substitute whichever version you prefer; this was as of 2020-08-07
  HUGO_ENV = "production"
  